### ISSUE TITLE
Concatenation?

### ISSUE THREAD

**Issue by Nv7-GitHub** [trodevel/convimp3#1]
I have an directory with mp3 files (001.mp3, 002.mp3, 003.mp3, etc.). I want to concatenate them into one mp3 file (main.mp3). I do not care about re-encoding, you can re-encode it if you want. Is there a way to concatenate them with this library? Is there a way to concatenate them with modifications to this library? I am making a program that requires mp3 concatenation and I would appreciate it. In addition, I would also appreciate it if you could give me a list of things I need to download and how to set this up. Thanks!

**Comment by trodevel** [comment]
Unfortunately not. This library is dedicated for a simple wav-to-mp3 conversion and vice versa. You may use a workaround: convert files to WAV and combine them into a single file using the wave library (https://github.com/trodevel/wave) and then convert them again into MP3.
